### ISSUE TITLE
Any example of usage?

### ISSUE THREAD

**Issue by Pureaznangel** [dotJEM/json-validation#18]
Would you give me an example how to use it please?

**Comment by jeme** [comment]
There is a basic example in the readme, it doesn't cover all aspects but it should get you started.
You may also look through the integration test project to find small samples of various aspects.

If you have any specific questions. Feel free to clarify.

**Comment by Pureaznangel** [comment]
> There is a basic example in the readme, it doesn't cover all aspects but it should get you started. You may also look through the integration test project to find small samples of various aspects.
> 
> If you have any specific questions. Feel free to clarify.

Hello Sir, I've this method as below use to check the response Json. But seem it failed with this case:

{
  "error": 0,
  "data": {}
}

my method:


public static bool IsNullOrEmptyValue(this JToken token)
        {
            return (token == null) ||
                (token.Type == JTokenType.Array && !token.HasValues) ||
                (token.Type == JTokenType.Object && !token.HasValues) ||
                (token.Type == JTokenType.String && token.ToString() == String.Empty) ||
                (token.Type == JTokenType.Date && token.Value<DateTime>() == Convert.ToDateTime("1899-12-30T00:00:00")) ||
                (token.Type == JTokenType.Boolean && token.Value<bool>() == false) ||
                (token.Type == JTokenType.Integer && token.Value<int>() == 0) ||
                (token.Type == JTokenType.Float && token.Value<double>() == 0.0) ||
                (token.Type == JTokenType.Property && ((JProperty)token).Value.ToString() == String.Empty) ||
                (token.Type == JTokenType.Null) ||
                (token.Type == JTokenType.Undefined);
        }

How can I re-write it to use this class to verify for the json is NOT EMPTY And NOT NULL? Thank you for your support.

**Comment by Pureaznangel** [comment]
> There is a basic example in the readme, it doesn't cover all aspects but it should get you started. You may also look through the integration test project to find small samples of various aspects.
> 
> If you have any specific questions. Feel free to clarify.

Hello Sir,

Why does it return False while data is currently empty? Please help me to perform this test correctly. Thanks

static void Main(string[] args)
        {

            var json = "{\"error\":0,\"data\":{}}";
            var Object = JObject.Parse(json);

            //Console.WriteLine(Object.ContainsKey("data"));
            //Console.WriteLine(Object["data"].HasValues);

            ValidatorResult result = new Validator().Validate(Object, null);

            Console.WriteLine(result.Describe());
            Console.WriteLine(result.IsValid);

            Console.ReadKey();
        }

        public class Validator : JsonValidator
        {
            public Validator()
            {
                When(Any)
                    .Then(Field("data", Is.Required()
                    & Must.Be.Object()
                    & !Must.Be.NullOrEmpty()));
            }
        }


![image](https://user-images.githubusercontent.com/41410414/225225532-8d7cc3c1-43a8-4ad8-9d45-da0581546a2f.png)

**Comment by jeme** [comment]
That is because of the way NullOrEmpty is implemented: https://github.com/dotJEM/json-validation/blob/master/DotJEM.Json.Validation/Constraints/Common/NullOrEmptyConstraint.cs

With !Must.Be.NullOrEmpty() your asking that data must not be null or empty, (you negate the constraint, that is fine, there is also Must.Have.Value() which is the opposite to give a bit of flexibility in the wording). - And `{}` is considered to be empty.

If an empty object should be accepted, yet null would not be, then required should be enough.
```csharp
public class Validator : JsonValidator
{
    public Validator()
    {
        When(Any).Then(Field("data", Is.Required() & Must.Be.Object()));
    }
}

ValidatorResult result = new Validator().Validate(JObject.Parse("{ 'error':0,'data':{  }}"), null); //PASS
```



Otherwise the validator requires your data object has at least one property:
```csharp
ValidatorResult result = new Validator().Validate(JObject.Parse("{ 'error':0,'data':{ 'me': 'OK' }}"), null); //PASS
```

**Comment by Pureaznangel** [comment]
> That is because of the way NullOrEmpty is implemented: https://github.com/dotJEM/json-validation/blob/master/DotJEM.Json.Validation/Constraints/Common/NullOrEmptyConstraint.cs
> 
> With !Must.Be.NullOrEmpty() your asking that data must not be null or empty, (you negate the constraint, that is fine, there is also Must.Have.Value() which is the opposite to give a bit of flexibility in the wording). - And `{}` is considered to be empty.
> 
> If an empty object should be accepted, yet null would not be, then required should be enough.
> 
> ```cs
> public class Validator : JsonValidator
> {
>     public Validator()
>     {
>         When(Any).Then(Field("data", Is.Required() & Must.Be.Object()));
>     }
> }
> 
> ValidatorResult result = new Validator().Validate(JObject.Parse("{ 'error':0,'data':{  }}"), null); //PASS
> ```
> 
> Otherwise the validator requires your data object has at least one property:
> 
> ```cs
> ValidatorResult result = new Validator().Validate(JObject.Parse("{ 'error':0,'data':{ 'me': 'OK' }}"), null); //PASS
> ```

Thank you for your comments.
