### ISSUE TITLE
Check the Json Object is null or empty

### ISSUE THREAD

**Issue by Pureaznangel** [dotJEM/json-validation#19]
May I ask how could I use this validator to check if if the input Json Object is completely Null or Empty?

e.g: { }

Regards,

**Comment by jeme** [comment]
So to be straight, the framework wasn't really designed for such cases.

However, technically, but perhaps a slightly hacky way, you can implement a SelfSelector as:

```CSharp
public class SelfSelector : FieldSelector
{
    public override string Alias { get; } = ".";
    public override IEnumerable<JTokenInfo> SelectTokens(JObject entity)
    {
        yield return new JTokenInfo(entity, this);
    }
}
```

Then use that as:
```CSharp
public class MyValidator : JsonValidator
{
    public MyValidator ()
    {
        When(Any).Then(new SelfSelector(), Must.Have.Value());
    }
}
```

This will give you (when null or empty):
```
Always
.
must have value - actual value was: {}
```

**Comment by Pureaznangel** [comment]
> So to be straight, the framework wasn't really designed for such cases.
> 
> However, technically, but perhaps a slightly hacky way, you can implement a SelfSelector as:
> 
> ```cs
> public class SelfSelector : FieldSelector
> {
>     public override string Alias { get; } = ".";
>     public override IEnumerable<JTokenInfo> SelectTokens(JObject entity)
>     {
>         yield return new JTokenInfo(entity, this);
>     }
> }
> ```
> 
> Then use that as:
> 
> ```cs
> public class MyValidator : JsonValidator
> {
>     public MyValidator ()
>     {
>         When(Any).Then(new SelfSelector(), Must.Have.Value());
>     }
> }
> ```
> 
> This will give you (when null or empty):
> 
> ```
> Always
> .
> must have value - actual value was: {}
> ```

Thanks for replying

Because sometimes the API response is null or just an empty JObject, I could use JObject != null && JObject["data"].HasValue everywhere, but this makes the code so confused. I try to use this framework to check them all.

Thanks!
